# Github Actions Marketplace Link
# https://github.com/marketplace/actions/amazon-ecr-login-action-for-github-actions

name: Build ECR Image

on:
#  pull_request:
#    branches:
#      - main
#    types: [closed]
  push:
    branches:
      - main

jobs:
  build_image:
    runs-on: ubuntu-latest
#    if: github.event.pull_request.merged == true

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: greatobi-ecr-dev
          IMAGE_TAG: "1.0"
        run: |
          echo "$ECR_REGISTRY"
          export ECR_REGISTRY=$ECR_REGISTRY
#          cd ./image/
#          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
#          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: test01
        run: |
          echo "$ECR_REGISTRY"

      - name: test02
        run: |
          echo "$ECR_REGISTRY"
